### PR TITLE
Add fullscreen and fit width buttons

### PR DESCRIPTION
**Pull request by louisgeisler**
Add a fullscreen button, mainly for smartphone
Add a full width button, for computer.

### CODE REVIEW

**Comment by MysteriesOfImmortalPuppetMaster** [comment]
thanks bro

**Comment by louisgeisler** [comment]
You're welcome — thanks to you to keeping it updated 🫡

Here is the list of some easy improvements you may do:
- Save theme and width preferences in localstorage
- Save the reading percentage progression of a chapter in localstorage and display a gradient on each chapters for the selection

Also, github usn't mean to store a lot of text, you should try to you google drive and google doc, create a public folder  [https://support.google.com/docs/answer/183965?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cembed-a-document-spreadsheet-or-presentation](Documentation) and them embed it into your website. It would be far more convenient and you may even let people annotate the text to propose modifications 👍

**Comment by MysteriesOfImmortalPuppetMaster** [comment]
Hi,
thanks for your interest in the site.
Truth be told, i have been working on a major redesign of the whole site, viewable here:  https://mysteriesofimmortalpuppetmaster.github.io/HomepageTEST/

so, i do not know how many of these changes i will be able to implement.

That being said,
Thanks for the tip with localstorage,
i didn't know this was a thing with github.

- reading progress will be hard but sounds cool
- URL, one of the major changes, all chapters will come with their own URL now.
like a real website :)

-selection groups will hopefully not be necessairy with the homepage existing


- for text,
idk, github is really nice to work with and push changes to, and a few megabytes of text shouldn't be a problem.
- for annotating changes., i guess we have a discord for that?




btw, i meant to ask,
how did you find my page?

**Comment by louisgeisler** [comment]
Honnestly, I prefered the previous version ^^' (your current version is too much complicated, you'll have hard time to maintain it...)

You didn't need much of change for the previous version to work with url targeting a chapter, you just need to catch the hash or the url id with js:
- https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams
- https://developer.mozilla.org/en-US/docs/Web/API/URL/hash

You're really are gooing into so much trouble for something (in my opinion) not worthy ^^'

Actually, reading progress is pretty easy, you just need to: Math.floor( window.scrollY / PageWidth * 100)
https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY

Localstorage ins't related to github, it pure javascript: https://www.w3schools.com/jsref/prop_win_localstorage.asp

I find it by discord, that's where you put the URL

**Pull request merged**
