### PR TITLE
Update 103.txt

### PR DESCRIPTION
**Pull request by Lucifer6704**

### CODE REVIEW

**Comment by MysteriesOfImmortalPuppetMaster** [comment]
slightly edited.
please do not do the quotation thing i mentioned last time.

If you want to merge these 2:

"Something happened."

"For sure."

do it like this in one line.

"Something happened. For sure."

**Comment by Lucifer6704** [comment]
Alright then

**Comment by MysteriesOfImmortalPuppetMaster** [comment]
Thanks.
I really appreciate your contribution.

**Comment by Lucifer6704** [comment]
No worries. If you want to add the first 100 chapters I can edit them too. I'll try to do 2-3 everyday :)

**Comment by MysteriesOfImmortalPuppetMaster** [comment]
Thanks for the offer. However, as there are already a lot of translations Chapter 0 - Chapter 100 freely available on the internet, I do not feel like it is worth the effort, both getting them and maintaining them.

**Pull request merged**
